const { withPodfile } = require("expo/config-plugins");

/**
 * Build the `fmt` pod as C++17.
 *
 * fmt 11.0.2 — pinned transitively by React Native 0.76 — does not compile with
 * Apple clang 21 (Xcode 26). fmt's own `format-inl.h` calls `FMT_STRING(...)`,
 * whose `basic_format_string` constructor is `consteval`, and clang 21 rejects
 * those calls as "not a constant expression":
 *
 *   ios/Pods/fmt/include/fmt/format-inl.h:59:24: error: call to consteval
 *   function 'fmt::basic_format_string<...>' is not a constant expression
 *
 * fmt already degrades gracefully on its own: `FMT_CPLUSPLUS < 201709L` sets
 * `FMT_USE_CONSTEVAL 0`, which makes that constructor non-consteval. So building
 * just this one pod as C++17 uses fmt's supported path rather than patching it.
 *
 * Scoped to the fmt target only — every other pod stays on C++20. That is safe
 * here because `FMT_STRING` / `FMT_COMPILE` are used nowhere else in the pod
 * tree (RCT-Folly ships `folly/portability/FmtCompile.h` but nothing includes
 * it), and consteval-ness affects compile-time checking, not ABI.
 *
 * Lives as a config plugin because `ios/` is gitignored and regenerated by
 * `expo prebuild`, so a hand-edited Podfile would not survive.
 *
 * Remove this once React Native ships fmt >= 11.1, which fixes the compiler
 * incompatibility upstream.
 */
// The snippet must run AFTER `react_native_post_install(...)`, which sets
// CLANG_CXX_LANGUAGE_STANDARD to c++20 on every pod target and would otherwise
// clobber this override.
const RN_POST_INSTALL_CALL = "react_native_post_install(";
const CALL_CLOSE = "\n    )";

const FMT_SNIPPET = `
    # fmt 11.0.2 does not build with Apple clang 21 (Xcode 26): its own
    # format-inl.h uses consteval format strings the compiler now rejects.
    # fmt turns consteval off itself below C++20, so build only this pod as
    # C++17. See plugins/withFmtCxx17.js. Remove when RN ships fmt >= 11.1.
    installer.pods_project.targets.each do |target|
      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end
`;

module.exports = function withFmtCxx17(config) {
  return withPodfile(config, (podfileConfig) => {
    const contents = podfileConfig.modResults.contents;

    if (contents.includes("target.name == 'fmt'")) {
      return podfileConfig;
    }

    const callIndex = contents.indexOf(RN_POST_INSTALL_CALL);
    if (callIndex === -1) {
      throw new Error(
        "withFmtCxx17: could not find `react_native_post_install(` in the Podfile."
      );
    }

    const closeIndex = contents.indexOf(CALL_CLOSE, callIndex);
    if (closeIndex === -1) {
      throw new Error(
        "withFmtCxx17: could not find the end of the `react_native_post_install(...)` call."
      );
    }

    const insertAt = closeIndex + CALL_CLOSE.length;
    podfileConfig.modResults.contents =
      contents.slice(0, insertAt) + FMT_SNIPPET + contents.slice(insertAt);

    return podfileConfig;
  });
};
